# Wi-Fi Display - from daisy - PKQ1.180917.001
#cp ../../xiaomi/daisy/proprietary/bin/wfdservice proprietary/bin
#cp ../../xiaomi/daisy/proprietary/etc/init/wfdservice.rc proprietary/etc
#cp ../../xiaomi/daisy/proprietary/etc/wfdconfigsink.xml proprietary/etc
#cp ../../xiaomi/daisy/proprietary/etc/wfdconfig.xml proprietary/etc
cp ../../xiaomi/daisy/proprietary/framework/WfdCommon.jar proprietary/framework
#cp ../../xiaomi/daisy/proprietary/lib64/extractors/libmmparser.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib64/libFileMux.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib64/libmmosal.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib64/libmmparser_lite.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib64/libwfdclient.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib64/libwfdnative.so proprietary/lib64
#cp ../../xiaomi/daisy/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/extractors/libmmparser.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libFileMux.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libmmosal.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libmmparser_lite.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libmmrtpdecoder.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libmmrtpencoder.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libOmxMux.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdavenhancements.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdclient.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdcodecv4l2.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdcommonutils.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdconfigutils.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdmminterface.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdmmsink.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/lib/libwfdmmsrc.so proprietary/lib
#cp ../../xiaomi/daisy/proprietary/priv-app/WfdService/WfdService.apk proprietary/priv-app/WfdService/
